version: "3.7"

services:
  calibre:
    image: linuxserver/calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.calibre-${NUMBER:-1}.rule=Host(`${DOMAIN:-calibre.localhost}`)
        - traefik.http.routers.calibre-${NUMBER:-1}.entrypoints=${SCHEME:-http}
        - traefik.http.routers.calibre-${NUMBER:-1}.service=calibre-${NUMBER:-1}
        - traefik.http.routers.calibre-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.calibre-${NUMBER:-1}.loadbalancer.server.port=8083
    volumes:
      - ${VOLUME_PATH}config:/config
      - ${VOLUME_PATH}books:/books

volumes:
  config:
  books:

networks:
  internal:
    driver: overlay
    attachable: true
  default:
    external: true
    name: traefik-net
