version: '3.7'

services:
  app:
    image: hackmdio/hackmd:${VERSION:-2.3.2}
    volumes:
      - ${VOLUME_PATH}uploads:/home/hackmd/app/public/uploads
    environment:
      - CMD_ALLOW_FREEURL=true
      - CMD_ALLOW_EMAIL_REGISTER=${CMD_ALLOW_EMAIL_REGISTER:-true}
      - CMD_DEFAULT_PERMISSION=${CMD_DEFAULT_PERMISSION:-editable}
      - CMD_DB_URL=postgres://codimd:myp@ssw0rd@postgres:5432/codimd
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.codimd-${NUMBER:-1}.rule=Host(`${DOMAIN:-codimd.localhost}`)
        - traefik.http.routers.codimd-${NUMBER:-1}.entrypoints=${SCHEME:-http}
        - traefik.http.routers.codimd-${NUMBER:-1}.service=codimd-${NUMBER:-1}
        - traefik.http.routers.codimd-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.codimd-${NUMBER:-1}.loadbalancer.server.port=3000
    networks:
      - internal
      - traefik

  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=codimd
      - POSTGRES_PASSWORD=myp@ssw0rd
      - POSTGRES_DB=codimd
    volumes:
      - ${VOLUME_PATH}postgres:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  postgres:
  uploads:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
