version: '3.7'

services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=codimd
      - POSTGRES_PASSWORD=mypassw0rd
      - POSTGRES_DB=codimd
    volumes:
      - ${VOLUME_PATH}postgres:/var/lib/postgresql/data
    networks:
      - internal

  app:
    image: hackmdio/hackmd:${VERSION:-1.3.1-alpine}
    environment:
      - HMD_DB_URL=postgres://codimd:mypassw0rd@postgres:5432/codimd
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.codimd-${NUMBER:-1}.rule=Host(`${DOMAIN:-codimd.localhost}`)
        - traefik.http.routers.codimd-${NUMBER:-1}.entrypoints=${SCHEME:-http}
        - traefik.http.routers.codimd-${NUMBER:-1}.service=codimd-${NUMBER:-1}
        - traefik.http.routers.codimd-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.codimd-${NUMBER:-1}.loadbalancer.server.port=3000
    networks:
      - internal
      - traefik

volumes:
  postgres:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
