# prosodyctl --config /config/prosody.cfg.lua register username meet.jitsi password

version: '3.7'

x-defaults: &defaults
  environment:
    - DISABLE_HTTPS=1
    - TZ=Europe/Paris
    - PUBLIC_URL=${SCHEME:-http}://${DOMAIN:-jitsi.localhost}
    - ENABLE_LETSENCRYPT=0
    - DOCKER_HOST_ADDRESS=${DOCKER_HOST_ADDRESS}

    - ENABLE_AUTH=${ENABLE_AUTH:-1}
    - AUTH_TYPE=${AUTH_TYPE:-internal}
    - ENABLE_GUESTS=${ENABLE_GUESTS:-1}

    - XMPP_DOMAIN=meet.jitsi
    - XMPP_SERVER=xmpp.meet.jitsi
    - XMPP_BOSH_URL_BASE=http://xmpp.meet.jitsi:5280
    - XMPP_AUTH_DOMAIN=auth.meet.jitsi
    - XMPP_MUC_DOMAIN=muc.meet.jitsi
    - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
    - XMPP_GUEST_DOMAIN=guest.meet.jitsi
    - XMPP_MODULES=
    - XMPP_MUC_MODULES=
    - XMPP_INTERNAL_MUC_MODULES=

    - JVB_BREWERY_MUC=jvbbrewery
    - JVB_AUTH_USER=jvb
    - JVB_AUTH_PASSWORD=myp@ssw0rd
    - JVB_STUN_SERVERS=stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302 # TODO: Remove Google
    - JVB_TCP_PORT=${JVB_TCP_PORT:-4443}
    - JVB_PORT=${JVB_UDP_PORT:-10000}
    - JVB_TCP_HARVESTER_DISABLED=${JVB_TCP_HARVESTER_DISABLED:-false}

    - JICOFO_COMPONENT_SECRET=mys3cr37
    - JICOFO_AUTH_USER=focus
    - JICOFO_AUTH_PASSWORD=myp@ssw0rd
    - JIGASI_XMPP_USER=jigasi
    - JIGASI_XMPP_PASSWORD=myp@ssw0rd
    - JIGASI_BREWERY_MUC=jigasibrewery
    - JIGASI_PORT_MIN=20000
    - JIGASI_PORT_MAX=20050

    - XMPP_RECORDER_DOMAIN=recorder.meet.jitsi

services:
  web:
    <<: *defaults
    image: jitsi/web
    volumes:
      - ${VOLUME_PATH}web:/config
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.jitsi-${NUMBER:-1}.rule=Host(`${DOMAIN:-jitsi.localhost}`)
        - traefik.http.routers.jitsi-${NUMBER:-1}.entrypoints=${SCHEME:-http}
        - traefik.http.routers.jitsi-${NUMBER:-1}.service=jitsi-${NUMBER:-1}
        - traefik.http.routers.jitsi-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.jitsi-${NUMBER:-1}.loadbalancer.server.port=80
      placement:
        constraints: [node.hostname==manager-prod-1]
    networks:
      traefik:
      internal:
        aliases:
          - meet.jitsi

  prosody:
    <<: *defaults
    image: jitsi/prosody
    volumes:
      - ${VOLUME_PATH}prosody:/config
    networks:
      internal:
        aliases:
          - xmpp.meet.jitsi

  jicofo:
    <<: *defaults
    image: jitsi/jicofo
    volumes:
      - ${VOLUME_PATH}jicofo:/config
    networks:
      - internal

  jvb:
    <<: *defaults
    image: jitsi/jvb
    ports:
      - target: ${JVB_UDP_PORT:-10000}
        published: ${JVB_UDP_PORT:-10000}
        protocol: udp
        mode: host
      - target: ${JVB_TCP_PORT:-4443}
        published: ${JVB_TCP_PORT:-4443}
        protocol: tcp
        mode: host
    volumes:
      - ${VOLUME_PATH}jvb:/config
    deploy:
      update_config:
        order: stop-first
      placement:
        constraints: [node.hostname==manager-prod-1]
    networks:
      - internal
      - traefik

volumes:
  web:
  prosody:
  jicofo:
  jvb:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
