version: '3.7'

services:
  mailserver:
    image: mailserver/docker-mailserver:${VERSION:-latest}
    ports:
      - {target: 25, published: 25, mode: host, protocol: tcp}
      - {target: 143, published: 143, mode: host, protocol: tcp}
      - {target: 587, published: 587, mode: host, protocol: tcp}
      - {target: 993, published: 993, mode: host, protocol: tcp}
    volumes:
      - ${VOLUME_PATH}maildata:/var/mail
      - ${VOLUME_PATH}mailstate:/var/mail-state
      - ${VOLUME_PATH}config:/tmp/docker-mailserver/
      - ${VOLUME_PATH}certs:/certs/
    environment:
      - OVERRIDE_HOSTNAME=${DOMAIN:-mail.domaine.fr}
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=0
      - ONE_DIR=1
      - DMS_DEBUG=0
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/certs/certs/${DOMAIN:-mail.domaine.fr}.crt
      - SSL_KEY_PATH=/certs/private/${DOMAIN:-mail.domaine.fr}.key
      - POSTFIX_MESSAGE_SIZE_LIMIT=${POSTFIX_MESSAGE_SIZE_LIMIT:-20480000}
      # - SRS_SECRET=${SRS_SECRET}
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    deploy:
      mode: ${MODE:-replicated}
      placement:
        constraints: [node.role==manager]

  rainloop:
    image: hardware/rainloop:latest
    volumes:
      - ${VOLUME_PATH}rainloop:/rainloop/data
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.rainloop-${NUMBER:-1}.rule=Host(`${DOMAIN:-rainloop.localhost}`)
        - traefik.http.routers.rainloop-${NUMBER:-1}.entrypoints=${SCHEME:-http}
        - traefik.http.routers.rainloop-${NUMBER:-1}.service=rainloop-${NUMBER:-1}
        - traefik.http.routers.rainloop-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.rainloop-${NUMBER:-1}.loadbalancer.server.port=8888
    networks:
      - traefik

volumes:
  rainloop:
  config:
  certs:
  maildata:
  mailstate:

networks:
  traefik:
    external: true
    name: traefik-net
