version: '3.7'

services:
  mailserver:
    image: tvial/docker-mailserver:latest
    ports:
      - { target: 25, published: 25, mode: host, protocol: tcp }
      - { target: 143, published: 143, mode: host, protocol: tcp }
      - { target: 587, published: 587, mode: host, protocol: tcp }
      - { target: 993, published: 993, mode: host, protocol: tcp }
    volumes:
      - ${VOLUME_PATH}maildata:/var/mail
      - ${VOLUME_PATH}mailstate:/var/mail-state
      - ${VOLUME_PATH}config:/tmp/docker-mailserver/
      - ${VOLUME_PATH}certs:/certs/
    environment:
      - OVERRIDE_HOSTNAME=${DOMAIN:-mail.domaine.fr}
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=0
      - ONE_DIR=1
      - DMS_DEBUG=0
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/certs/certs/${DOMAIN:-mail.domaine.fr}.crt
      - SSL_KEY_PATH=/certs/private/${DOMAIN:-mail.domaine.fr}.key
      - POSTFIX_MESSAGE_SIZE_LIMIT=${POSTFIX_MESSAGE_SIZE_LIMIT:-20480000}
      # - SRS_SECRET=${SRS_SECRET}
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    deploy:
      mode: ${MODE:-replicated}
      placement:
        constraints: [node.role==manager]

  rainloop:
    image: hardware/rainloop:latest
    volumes:
      - ${VOLUME_PATH}rainloop:/rainloop/data
    deploy:
      labels:
        - traefik.port=8888
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-mail.domaine.fr},${OTHER_DOMAINS}
    networks:
      - traefik

volumes:
  rainloop:
  config:
  certs:
  maildata:
  mailstate:

networks:
  traefik:
    external: true
    name: traefik-net
