version: '3.7'

services:
  mautic:
    image: ethibox/mautic:${VERSION:-2.16.2}
    volumes:
      - ${VOLUME_PATH}data:/var/www/html
    environment:
      - MAUTIC_DB_HOST=mariadb
      - MAUTIC_DB_NAME=mautic
      - MAUTIC_DB_USER=mautic
      - MAUTIC_DB_PASSWORD=myp@ssw0rd
      - MAUTIC_TRUSTED_PROXIES=0.0.0.0/0
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.mautic-${NUMBER:-1}.rule=Host(`${DOMAIN:-mautic.localhost}`)
        - traefik.http.routers.mautic-${NUMBER:-1}.entrypoints=${SCHEME:-http}
        - traefik.http.routers.mautic-${NUMBER:-1}.service=mautic-${NUMBER:-1}
        - traefik.http.routers.mautic-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.mautic-${NUMBER:-1}.loadbalancer.server.port=80
    networks:
      - traefik
      - internal

  mariadb:
    image: mariadb:10.3.14
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=myp@ssw0rd
      - MYSQL_DATABASE=mautic
      - MYSQL_USER=mautic
      - MYSQL_PASSWORD=myp@ssw0rd
    networks:
      - internal

volumes:
  mariadb:
  data:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
