version: '3.7'

services:
  nginx:
    image: ethibox/nginx-proxy:latest
    command:
      - /bin/sh
      - -c
      - |
        cp /etc/nginx/nginx-nextcloud.conf /etc/nginx/nginx.conf
        sed -i -e 's/app:9000/'$$STACK_NAME'_app:9000/g' /etc/nginx/nginx.conf
        nginx -g 'daemon off;'
    environment:
      - STACK_NAME={{ index .Service.Labels "com.docker.stack.namespace" }}
    volumes:
      - ${VOLUME_PATH}nextcloud:/var/www/html:cached
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.nextcloud-${NUMBER:-1}.rule=Host(`${DOMAIN:-nextcloud.localhost}`)
        - traefik.http.routers.nextcloud-${NUMBER:-1}.entrypoints=${SCHEME:-http}
        - traefik.http.routers.nextcloud-${NUMBER:-1}.service=nextcloud-${NUMBER:-1}
        - traefik.http.routers.nextcloud-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.routers.nextcloud-${NUMBER:-1}.middlewares=nextcloud-${NUMBER:-1},nextcloud-${NUMBER:-1}-redirect
        - traefik.http.services.nextcloud-${NUMBER:-1}.loadbalancer.server.port=80
        - traefik.http.middlewares.nextcloud-${NUMBER:-1}.headers.customResponseHeaders.Referrer-Policy=no-referrer
        - traefik.http.middlewares.nextcloud-${NUMBER:-1}.headers.customResponseHeaders.Strict-Transport-Security=max-age=31536000
        - traefik.http.middlewares.nextcloud-${NUMBER:-1}.headers.customResponseHeaders.X-Frame-Options=SAMEORIGIN
        - traefik.http.middlewares.nextcloud-${NUMBER:-1}-redirect.redirectregex.regex=/.well-known/(card|cal)dav
        - traefik.http.middlewares.nextcloud-${NUMBER:-1}-redirect.redirectregex.replacement=/remote.php/dav/
        - traefik.http.middlewares.nextcloud-${NUMBER:-1}-redirect.redirectregex.permanent=true
    networks:
      - internal
      - traefik

  app:
    image: nextcloud:${VERSION:-19.0.1-fpm-alpine}
    command:
      - /bin/sh
      - -c
      - |
        sleep 10
        apk add --no-cache sudo
        sudo -u www-data php occ --no-warnings db:add-missing-indices
        sudo -u www-data php occ --no-warnings db:convert-filecache-bigint
        sudo -u www-data php occ --no-warnings config:system:set trusted_proxies 0 --value="172.xx.0.x"
        sudo -u www-data php occ --no-warnings config:system:set overwriteprotocol --value="${SCHEME:-http}"
        sudo -u www-data php occ --no-warnings config:system:set overwrite.cli.url --value="${SCHEME:-http}://${DOMAIN:-nextcloud.localhost}"
        mkdir -p config && wget -O config/objectstore.config.php https://github.com/ethibox/stacks/raw/master/configs/objectstore.config.php
        php-fpm
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-myp@ssw0rd}
      - NEXTCLOUD_TRUSTED_DOMAINS=${DOMAIN:-nextcloud.localhost} nginx ${TRUSTED_DOMAINS}
      - NEXTCLOUD_UPDATE=${NEXTCLOUD_UPDATE:-1}
      - FORCE_LANGUAGE=${FORCE_LOCALE:-fr}
      - ENABLE_S3=${ENABLE_S3:-false}
      - S3_BUCKET=${S3_BUCKET}
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}
      - S3_REGION=${S3_REGION}
      - S3_HOSTNAME=${S3_HOSTNAME}
      - S3_PORT=${S3_PORT:-443}
      - S3_USE_SSL=${S3_USE_SSL:-true}
      - S3_AUTOCREATE=${S3_AUTOCREATE:-true}
      - S3_USE_PATH_STYLE=${S3_USE_PATH_STYLE:-true}
      - S3_OBJECT_PREFIX=${S3_OBJECT_PREFIX:-urn:oid:}
    volumes:
      - ${VOLUME_PATH}nextcloud:/var/www/html:cached
    networks:
      - internal

  mariadb:
    image: mariadb:10.3.12
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-myp@ssw0rd}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-myp@ssw0rd}
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql
    networks:
      - internal

volumes:
  nextcloud:
  mariadb:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
