# /var/www/wallabag/bin/console doctrine:migrations:migrate --env=prod --no-interaction
# ./scripts/install.sh prod --ignore-root-warning

version: '3.7'

services:
  web:
    image: wallabag/wallabag:${VERSION:-2.4.1}
    volumes:
      - ${VOLUME_PATH}data:/var/www/wallabag/data
    environment:
      SYMFONY__ENV__DOMAIN_NAME: ${SCHEME:-http}://${DOMAIN:-wallabag.localhost}
      SYMFONY__ENV__FOSUSER_CONFIRMATION: "false"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.wallabag-${NUMBER:-1}.rule=Host(`${DOMAIN:-wallabag.localhost}`)
        - traefik.http.routers.wallabag-${NUMBER:-1}.entrypoints=${SCHEME:-http}
        - traefik.http.routers.wallabag-${NUMBER:-1}.service=wallabag-${NUMBER:-1}
        - traefik.http.routers.wallabag-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.wallabag-${NUMBER:-1}.loadbalancer.server.port=80

volumes:
  data:

networks:
  default:
    external: true
    name: traefik-net
