global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['localhost:9090']

  - job_name: ethibox
    metrics_path: /metrics
    static_configs:
      - targets: ['ethibox_metrics:9090']

  - job_name: node-exporter
    dns_sd_configs:
    - names:
      - tasks.node-exporter
      type: A
      port: 9100

  - job_name: cadvisor
    dns_sd_configs:
    - names:
      - tasks.cadvisor
      type: A
      port: 8080
